name: Run Python Tests

# Trigger workflow on push and pull request events
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python environment (3.10)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies from requirements.txt and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Run pytest on the codebase
      - name: Run Tests
        run: pytest
