name: 🚀 Deploy InsightHub to Streamlit Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v3

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: 📦 Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ✅ Run Lint & Tests
      run: |
        flake8 . --ignore=E501
        pytest tests/

    - name: 🚀 Deploy to Streamlit Cloud (trigger by push)
      run: echo "🔔 Ready to deploy! (Trigger Streamlit manually if needed)"
